unique_name: Product
object_type: dimension
label: Product
hierarchies:
  - unique_name: Product Hierarchy
    label: Product Hierarchy
    levels:
      - unique_name: Product Category
      - unique_name: Product Item
level_attributes:
  - unique_name: Product Category
    label: Product Category
    contains_unique_names: false
    dataset: dimproduct
    is_unique_key: false
    key_columns:
      - productline
    name_column: productline
    sort_column: empty_value
  - unique_name: Product Item
    label: Product Item
    contains_unique_names: false
    dataset: dimproduct
    is_unique_key: false
    key_columns:
      - productkey
    name_column: englishproductname
type: standard
